
name: vigil_eye
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  # UI and Animation
  cupertino_icons: ^1.0.2

  # Image handling
  image_picker: ^1.0.4

  # Communication
  url_launcher: ^6.2.1
  another_telephony: ^0.4.1


  # Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3

  # RabbitMQ
  dart_amqp: ^0.3.1

  # Audio and Vibration
  audioplayers: ^5.2.1
  vibration: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/sounds.mp3
    - assets/animations.json